<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>ContextMenuWhileSearching</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <SPTPath>D:\Games\EscapeFromTarkov5.0</SPTPath>
  </PropertyGroup>

  <ItemGroup>
    <!-- BepInEx core -->
    <Reference Include="BepInEx.Core">
      <HintPath>$(SPTPath)\BepInEx\core\BepInEx.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>$(SPTPath)\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(SPTPath)\BepInEx\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(SPTPath)\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
        <Reference Include="BepInEx.Unity.Common">
      <HintPath>$(SPTPath)\BepInEx\core\BepInEx.Unity.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <!-- Game assemblies (interop) -->
    <Reference Include="Assembly-CSharp">
      <HintPath>$(SPTPath)\BepInEx\interop\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>$(SPTPath)\BepInEx\interop\Comfort.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(SPTPath)\BepInEx\interop\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(SPTPath)\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(SPTPath)\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>$(SPTPath)\BepInEx\interop\Sirenix.Serialization.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
